[project]
name = "oio"
dynamic = ["authors", "classifiers", "dependencies", "entry-points", "readme", "scripts", "version"]

[build-system]
requires = ["black", "setuptools >= 47.1.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
