version: v1.0
name: oio-sds-coverage
environment: oio-sds-env
jobs:
  - job: Collect code coverage statistics
    steps:

      - name: Checkout application
        checkout: '{{ .cds.workspace }}'

      - name: Install dependencies
        script:
          - apt update
          - apt install -y python3-virtualenv virtualenv lcov
          - virtualenv -p /usr/bin/python3 $HOME/oiovenv
          - . $HOME/oiovenv/bin/activate
          - pip install --upgrade pip virtualenv coverage

      - artifactDownload:
          path: '{{.cds.workspace}}'
          pattern: '.coverage.*'
          tag: '{{.cds.version}}'

      - name: Aggregate Python coverage statistics
        script:
          - . $HOME/oiovenv/bin/activate
          - cd {{.cds.workspace}}
          - coverage combine .coverage.*
          - coverage report --omit="/usr/lib/python3*" --skip-empty --ignore-errors > coverage-report-py.txt
          - worker upload --tag='{{.cds.version}}' {{.cds.workspace}}/coverage-report-py.txt
          - coverage xml --omit="/usr/lib/python3*" --skip-empty --ignore-errors -o coverage-py.xml
          - coverage html --omit="/usr/lib/python3*" --skip-empty --ignore-errors -d coverage-report-py
          - rm -f coverage-report-py.txt

      - optional: true
        coverage:
          format: cobertura
          minimum: "70"
          path: '{{.cds.workspace}}/coverage-py.xml'

      - name: Aggregate C coverage statistics
        script:
          - cd {{.cds.workspace}}
          - worker download --tag="{{.cds.version}}" --pattern="cmake_coverage.*"
          - sed -i -r -e 's,^SF:/tmp/[^/]+/run/(.+)$,SF:\1,g' cmake_coverage.*
          - echo cmake_coverage.* | xargs printf -- '-a %s\n' | xargs lcov -o cmake_coverage.all
          - genhtml --ignore-errors "source" --output-directory coverage-report-c cmake_coverage.all

      - name: Create coverage archive
        script:
          - cd {{.cds.workspace}}
          - mkdir coverage
          - mv coverage-report-c coverage-report-py coverage/
          - echo '<!DOCTYPE html><html><a href="./coverage-report-c/">C coverage report</a><br/><a href="./coverage-report-py/">Python coverage report</a></body></html>' > coverage/index.html
          - tar -czf coverage-report.tar.gz coverage
          - worker upload --tag='{{.cds.version}}' coverage-report.tar.gz

      - name: Publish code coverage scores on CDS
        optional: true
        coverage:
          format: lcov
          minimum: "70"
          path: '{{.cds.workspace}}/cmake_coverage.all'

      - name: Publish code coverage reports on Artifactory
        optional: true
        OVH_Serve_Static_Files:
          destination: 'coverage/{{ .git.branch | replace "dev/" "develo/" | trunc 6 | replace "develo" "dev" }}/{{.cds.version}}'
          source: coverage

    requirements:
        - model: ubuntu-focal
