version: v1.0
name: oio-sds-root
jobs:
  - job: Update dependency cache
    steps:
      - name: Checkout application
        checkout: '{{ .cds.workspace }}'
      - name: Download nonstandard dependencies
        script: |+
          #!/bin/bash
          set -x
          . .cds/versions
          fdbtag="fdb-${FDB_VERSION}"
          if ! worker cache pull $fdbtag
          then
            mkdir fdb-packages
            cd fdb-packages
            wget -q \
              https://github.com/apple/foundationdb/releases/download/${FDB_VERSION}/foundationdb-clients_${FDB_VERSION}-1_amd64.deb \
              https://github.com/apple/foundationdb/releases/download/${FDB_VERSION}/foundationdb-server_${FDB_VERSION}-1_amd64.deb
            cd ..
            worker cache push $fdbtag fdb-packages
          fi
    requirements:
      # - binary: wget
      - model: Debian12-Container

  - job: Compile tinyproxy
    steps:
      - name: Compile tinyproxy
        script: |+
          #!/bin/bash
          TINYPROXY_VERSION="1.11.2"
          tag="tinyproxy"
          set -ex
          if ! worker cache pull $tag
          then
            apt-get -q update
            apt-get -q -y install build-essential
            curl -s -S -L --output tinyproxy.tar.gz \
              https://github.com/tinyproxy/tinyproxy/releases/download/${TINYPROXY_VERSION}/tinyproxy-${TINYPROXY_VERSION}.tar.gz
            tar -xf tinyproxy.tar.gz
            cd tinyproxy-${TINYPROXY_VERSION}
            ./configure && make -j2
            worker cache push $tag src/tinyproxy
          fi
    requirements:
      - model: ubuntu-focal
