version: v1.0
name: oio-sds-test-fast
jobs:
  - job: Run fast tests
    steps:

      - name: Checkout application
        checkout: '{{ .cds.workspace }}'

      - name: Clone external-packages
        script:
          - eval $(worker key install --env-git proj-ssh-openio)
          - git clone {{ .cds.proj.STASH_URL }}/openio/external-packages.git /external-packages

      - name: Install dependencies
        script: |+
          #!/bin/bash
          set -x
          sudo add-apt-repository ppa:longsleep/golang-backports
          curl http://mirror.openio.io/pub/repo/openio/APT-GPG-KEY-OPENIO-0 | apt-key add -
          apt-add-repository "deb http://mirror.openio.io/pub/repo/openio/sds/19.04/ubuntu/ bionic/"
          apt install -y $(tr '\n' ' ' < .cds/deps-ubuntu-bionic.txt)
          mkdir /tmp/oio
          virtualenv -p /usr/bin/python2 $HOME/oioenv
          . $HOME/oioenv/bin/activate
          pip install --upgrade pip setuptools virtualenv tox -r all-requirements.txt -r test-requirements.txt

      - name: Run fast tests
        script:
          - . $HOME/oioenv/bin/activate
          - ./tools/oio-travis-failfast.sh

      - name: Run unit tests
        script:
          - . $HOME/oioenv/bin/activate
          - ./tools/oio-travis-unit.sh

    requirements:
      - model: openio-debbuild-18.04
