version: v1.0
name: oio-sds-test-functional
environment: oio-sds-env
jobs:
  - job: Run functional tests
    steps:

      - name: Checkout application
        checkout: '{{ .cds.workspace }}'

      - name: Install dependencies
        script: |+
          #!/bin/bash
          set -x
          echo "deb [trusted=yes] http://read:{{.cds.proj.private_ovh_objectstorage_openio_read_password}}@last-private-ovh-objectstorage-openio.snap-priv.mirrors.ovh.net/ubuntu focal/main main" >> /etc/apt/sources.list.d/obsto.list
          echo "deb [trusted=yes] http://last-public-ovh-pcs.snap.mirrors.ovh.net/ubuntu focal main" >> /etc/apt/sources.list.d/obsto.list
          apt update
          apt install -y $(tr '\n' ' ' < .cds/deps-ubuntu-focal.txt) {{ .cds.env.GO_PACKAGE }} {{ .cds.env.PYTHON_PACKAGE }} {{ .cds.env.ZOOKEEPER_PACKAGE }}
          systemctl stop apache2.service redis.service
          systemctl disable apache2.service redis.service
          # Configure environment
          echo "export PATH=/opt/{{ .cds.env.GO_PACKAGE }}/bin:$PATH" > $HOME/oio-env.sh
          echo "export ZOOBINDIR=/opt/{{ .cds.env.ZOOKEEPER_PACKAGE }}/bin"  >> $HOME/oio-env.sh
          echo "export LD_LIBRARY_PATH=/opt/{{ .cds.env.GO_PACKAGE }}/lib:/opt/{{ .cds.env.ZOOKEEPER_PACKAGE }}/lib:/tmp/oio/lib" >> $HOME/oio-env.sh
          source $HOME/oio-env.sh
          mkdir /tmp/oio
          /opt/{{ .cds.env.PYTHON_PACKAGE }}/bin/python3 -m pip install --upgrade pip
          /opt/{{ .cds.env.PYTHON_PACKAGE }}/bin/python3 -m venv $HOME/oiovenv
          . $HOME/oiovenv/bin/activate
          env
          pip install --upgrade pip setuptools virtualenv tox -r test-requirements.txt

          wget -q https://github.com/apple/foundationdb/releases/download/${FDB_VERSION}/foundationdb-clients_${FDB_VERSION}-1_amd64.deb
          wget -q https://github.com/apple/foundationdb/releases/download/${FDB_VERSION}/foundationdb-server_${FDB_VERSION}-1_amd64.deb
          dpkg -i foundationdb-clients_${FDB_VERSION}-1_amd64.deb foundationdb-server_${FDB_VERSION}-1_amd64.deb
          systemctl stop foundationdb.service
          systemctl disable foundationdb.service

      - name: Run functional tests
        script:
          - . $HOME/oio-env.sh
          - pgrep rsyslogd || rsyslogd &
          - sysctl -w kernel.core_pattern='/tmp/core.%p.%E'
          - ulimit -c unlimited
          - ulimit -n 8192
          - . $HOME/oiovenv/bin/activate
          - ./tools/oio-zk-cluster.sh bootstrap {{ .cds.env.ZK_CLUSTER }}
          - ./tools/oio-zk-cluster.sh start {{ .cds.env.ZK_CLUSTER }}
          - ./tools/oio-travis-suites.sh
          - ./tools/oio-zk-cluster.sh stop {{ .cds.env.ZK_CLUSTER }}

      - name: Save coverage information
        script:
          - mv '{{.cds.workspace}}/.coverage' '{{.cds.workspace}}/.coverage.{{.cds.env.TEST_SUITE}}'
          - mv '/tmp/cmake_coverage.output' '{{.cds.workspace}}/cmake_coverage.{{.cds.env.TEST_SUITE}}'
          - worker upload --tag='{{.cds.version}}' '{{.cds.workspace}}/.coverage.{{.cds.env.TEST_SUITE}}' '{{.cds.workspace}}/cmake_coverage.{{.cds.env.TEST_SUITE}}'

    requirements:
        - model: '{{ .cds.env.MODEL}}'
