version: v1.0
name: oio-sds-test-fast
jobs:
  - job: Run fast tests
    steps:

      - gitClone:
          branch: '{{ .git.branch }}'
          commit: '{{ .git.hash }}'
          depth: "false"
          directory: '{{ .cds.workspace }}'
          privateKey: proj-ssh-openio
          url: '{{ .git.url }}'

      - name: Install dependencies
        script: |+
          #!/bin/bash
          set -x
          echo "deb [trusted=yes] http://read:{{.cds.proj.private_ovh_objectstorage_openio_read_password}}@last-private-ovh-objectstorage-openio.snap-priv.mirrors.ovh.net/ubuntu focal/main main" >> /etc/apt/sources.list.d/obsto.list
          echo "deb [trusted=yes] http://last-public-ovh-pcs.snap.mirrors.ovh.net/ubuntu focal main" >> /etc/apt/sources.list.d/obsto.list
          apt update
          apt install -y $(tr '\n' ' ' < .cds/deps-ubuntu-focal.txt) {{ .cds.env.GO_PACKAGE }} {{ .cds.env.PYTHON_PACKAGE }} {{ .cds.env.ZOOKEEPER_PACKAGE }}
          systemctl stop apache2.service redis.service
          systemctl disable apache2.service redis.service
          # Configure environment
          echo "export PATH=/opt/{{ .cds.env.GO_PACKAGE }}/bin:/opt/{{ .cds.env.ZOOKEEPER_PACKAGE }}/bin:/opt/{{ .cds.env.PYTHON_PACKAGE }}/bin:$PATH" > $HOME/oio-env.sh
          echo "export ZOOBINDIR=/opt/{{ .cds.env.ZOOKEEPER_PACKAGE }}/bin"  >> $HOME/oio-env.sh
          echo "export LD_LIBRARY_PATH=/opt/{{ .cds.env.GO_PACKAGE }}/lib:/opt/{{ .cds.env.PYTHON_PACKAGE }}/lib:/opt/{{ .cds.env.ZOOKEEPER_PACKAGE }}/lib:/tmp/oio/lib" >> $HOME/oio-env.sh
          echo "export PYTHONPATH=$(find /opt/{{ .cds.env.PYTHON_PACKAGE }}/lib/ -name 'site-packages')" >> $HOME/oio-env.sh
          source $HOME/oio-env.sh
          mkdir /tmp/oio
          virtualenv -p /opt/{{ .cds.env.PYTHON_PACKAGE }}/bin/python3 $HOME/oiovenv
          . $HOME/oiovenv/bin/activate
          pip install --upgrade pip setuptools virtualenv tox -r all-requirements.txt -r test-requirements.txt
          wget -q https://www.foundationdb.org/downloads/${FDB_VERSION}/ubuntu/installers/foundationdb-clients_${FDB_VERSION}-1_amd64.deb
          wget -q https://www.foundationdb.org/downloads/${FDB_VERSION}/ubuntu/installers/foundationdb-server_${FDB_VERSION}-1_amd64.deb
          dpkg -i foundationdb-clients_${FDB_VERSION}-1_amd64.deb foundationdb-server_${FDB_VERSION}-1_amd64.deb
          systemctl stop foundationdb.service
          systemctl disable foundationdb.service

      - name: Run fast tests
        script:
          - . $HOME/oio-env.sh
          - pgrep rsyslogd || rsyslogd &
          - . $HOME/oiovenv/bin/activate
          - ./tools/oio-travis-failfast.sh

      - name: Run unit tests
        script:
          - . $HOME/oio-env.sh
          - . $HOME/oiovenv/bin/activate
          - ./tools/oio-travis-unit.sh

    requirements:
      - model: Ubuntu-20.04-VM-b2-07
