version: v1.0
name: oio-sds-build
jobs:
  - job: Package for ubuntu/20.04
    steps:

      - gitClone:
          branch: '{{ .git.branch }}'
          commit: '{{ .git.hash }}'
          depth: "false"
          directory: '{{ .cds.workspace }}'
          privateKey: proj-ssh-openio
          url: '{{ .git.url }}'

      - name: Clone external-packages
        script:
          - eval $(worker key install --env-git proj-ssh-openio)
          - git clone {{ .cds.proj.STASH_URL }}/openio/external-packages.git /external-packages

      - name: Build package and upload
        script: |+
          #!/bin/bash
          exec &> >(tee -a package-20.04.log)
          trap 'worker upload package-20.04.log' EXIT
          cat $0
          set -x
          set -e
          . .cds/versions
          if [[ "{{ .git.branch }}" =~ ^dev/[a-z0-9]+/feature_ || "{{ .git.branch }}" =~ ^feature/ ]]; then
            export VERSION=1.${CDS_VERSION}-focal
            PACKAGE="{{ .git.branch }}"
            PACKAGE="${PACKAGE#dev/*/}" # remove dev/login*/ prefix
            PACKAGE="${PACKAGE//[^a-zA-Z0-9]/-}" # sanitize package name
            export PACKAGE="oio-sds-${PACKAGE}"
          else
            # dev or prod release
            export VERSION=1.0-focal
            PACKAGE=oio-sds
            if [[ "{{ .git.tag }}" =~  ^[0-9]+\. ]]; then
              PACKAGE=${PACKAGE}-{{ .git.tag }}
            else
              PACKAGE=${PACKAGE}-$(date +%Y%m%d%H%M).git{{ .git.hash.short }}
            fi
            if [ "{{ .git.branch }}" = "master" ]; then
              export OBSTO_BUILD="ovh${CDS_VERSION}"
            else
              export OBSTO_BUILD="ovhdev${CDS_VERSION}"
            fi
            export PACKAGE=${PACKAGE}-${OBSTO_BUILD}
          fi
          export REPO_SUBREPO=main
          export REPO_LIMIT=0
          export REPO_URL="https://{{ .cds.proj.drive_mirrors_objectstorage_openio_user }}:{{ .cds.proj.drive_mirrors_objectstorage_openio_password }}@{{ .cds.proj.drive_mirrors_hostname }}"
          make -f /external-packages/ubuntu/focal/Makefile.common install-apt-repo
          make -f /external-packages/ubuntu/focal/Makefile.common deb_changelog
          make -f /external-packages/ubuntu/focal/Makefile.common
          make -f /external-packages/ubuntu/focal/Makefile.common upload_to_artifacts
          make -f /external-packages/ubuntu/focal/Makefile.common upload_to_repo
    requirements:
      - model: openio-debbuild-20.04
